#
# SSL configuration
#
#server:
#    port: 8443
#    ssl:
#        key-store: src/main/resources/keystore.p12
#        key-store-password: elektromosLincoln
#        keyStoreType: PKCS12
#        keyAlias: worktime

#
# Caffeine configuration
#
spring:
    cache:
        caffeine:
            spec: expireAfterAccess=7200s
#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/worktime?useUnicode=yes&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#        username: ****
#        password: pwd